---
  title: Jan 2023 default run
  input:
    urls:
      pim.inputs:
        src_url: 'https://www.ons.gov.uk/file?uri=/economy/nationalaccounts/uksectoraccounts/datasets/inventorymethodpiminputs/january2023/piminput.xlsx'
      cofog.splits: 
        src_url: 'https://www.ons.gov.uk/file?uri=/economy/nationalaccounts/uksectoraccounts/methodologies/capitalstocksuserguideuk/splitcofog.xlsx'
      cvm.coverage: 
        src_url: 'https://www.ons.gov.uk/file?uri=/economy/nationalaccounts/uksectoraccounts/methodologies/capitalstocksuserguideuk/cvmcoveragetable.xlsx'
      agg.hierarchies: 
        src_url: 'https://www.ons.gov.uk/file?uri=/economy/nationalaccounts/uksectoraccounts/methodologies/capitalstocksuserguideuk/hierarchiessectorindustryasset.xlsx'
  run.params:
    save.points: true
    ref.period: Y2019Q4
    to.chain.from: Y1995Q1
    to.chain.to: Y2021Q4
    override.git.restriction: FALSE
  output:
    annual.estimates:
      write.out: true
      #options: csv, Rds NB: not in use yet
      format: csv
      #options: long, wide, both
      structure: long
    quarterly.estimates:
      write.out: true
      #options: csv, RDS - NB: not in use yet
      format: csv
      structure: long
    console.log:
      write.out: true
      log.per.script: true
